#sudo: required
cache:
  - apt

language: generic

virtualenv:
    system_site_packages: true

branches:
    only:
        - master

before_install:
  - sudo apt update
  - cd
  - sudo apt-get install curl
  - sudo apt-get install python-tk
  - curl 'https://raw.githubusercontent.com/facebookresearch/pyrobot/Develop/robots/LoCoBot/install/locobot_install_all_travis_ci.sh' > locobot_install_all.sh
  - pwd
  - chmod +x locobot_install_all.sh
  - ./locobot_install_all.sh -t sim_only -p 2

script:
  - source /opt/ros/kinetic/setup.bash
  - cd ~/low_cost_ws
  - source devel/setup.bash
  - source ~/pyenv_pyrobot/bin/activate
  - cd src/pyrobot/tests
  - python run_test.py --out_dir htmlcov/`git rev-parse HEAD` --nobrowser