version: 2.1

jobs:
  
  kinetic_install_ubuntu_16:
    resource_class: xlarge
    docker:
      - image: ros:kinetic-robot-xenial

    steps:
      - checkout            
      - run:
          name: Installer Python2
          command: |
            sudo apt-get install -y python-rosdep
            cd ~/project/robots/LoCoBot/install
            chmod +x locobot_install_all.sh
            ./locobot_install_all.sh -t sim_only -p 2
 
      - run:
          name: Installer Python3
          command: |
            source ~/.bashrc
            source /opt/ros/$ROS_DISTRO/setup.bash
            source ~/low_cost_ws/devel/setup.bash
            cd ~/project
            chmod +x install_pyrobot.sh
            ./install_pyrobot.sh -p 3
            cd ~/project/robots/LoCoBot
            source ~/pyenv_pyrobot_python3/bin/activate
            pip3 install --ignore-installed -r requirements_python3.txt
            deactivate

      - run:
          name: Run Gazebo in the background
          command: |
            sudo apt-get install -y xvfb
            Xvfb :1 -screen 0 1600x1200x16  &
            export DISPLAY=:1.0
            source ~/.bashrc
            source /opt/ros/$ROS_DISTRO/setup.bash
            source ~/low_cost_ws/devel/setup.bash
            roslaunch locobot_control main.launch use_sim:=true use_rviz:=false
          no_output_timeout: 1.00h
          background: true
      
      - run:
          name: Run tests in Python3
          command: |
            sleep 150 # Wait for Gazebo to properly spin up
            source ~/.bashrc
            cd ~/project/tests/
            chmod +x circleci_tests.sh
            ./circleci_tests.sh


  melodic_install_ubuntu_18:
    resource_class: xlarge
    docker:
      - image: ros:melodic-robot-bionic

    steps:
      - checkout            
      - run:
          name: Installer Python2
          command: |
            sudo apt-get install -y python-rosdep
            cd ~/project/robots/LoCoBot/install
            chmod +x locobot_install_all.sh
            ./locobot_install_all.sh -t sim_only -p 2
 
      - run:
          name: Installer Python3
          command: |
            source ~/.bashrc
            source /opt/ros/$ROS_DISTRO/setup.bash
            source ~/low_cost_ws/devel/setup.bash
            cd ~/project
            chmod +x install_pyrobot.sh
            ./install_pyrobot.sh -p 3
            cd ~/project/robots/LoCoBot
            source ~/pyenv_pyrobot_python3/bin/activate
            pip3 install --ignore-installed -r requirements_python3.txt
            deactivate
                       
      - run:
          name: Run Gazebo in the background
          command: |
            sudo apt-get install -y xvfb
            Xvfb :1 -screen 0 1600x1200x16  &
            export DISPLAY=:1.0
            source ~/.bashrc
            source /opt/ros/$ROS_DISTRO/setup.bash
            source ~/low_cost_ws/devel/setup.bash
            roslaunch locobot_control main.launch use_sim:=true use_rviz:=false
          no_output_timeout: 1.00h
          background: true
      
      - run:
          name: Run tests in Python3
          command: |
            sleep 150 # Wait for Gazebo to properly spin up
            source ~/.bashrc
            cd ~/project/tests/
            chmod +x circleci_tests.sh
            ./circleci_tests.sh


workflows:
  version: 2
  kinetic_and_melodic:
    jobs:
      - kinetic_install_ubuntu_16
      - melodic_install_ubuntu_18